# Generated by Django 3.2.9 on 2021-11-07 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mark', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.IntegerField()),
                ('punishment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsCamera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalogCameras.camera')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSupport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=120)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalogCameras.camera')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCamera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=120, unique=True)),
                ('holderFlash', models.BooleanField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelcameras', to='AnalogCameras.camera')),
            ],
        ),
        migrations.CreateModel(
            name='Leasing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AnalogCameras.client')),
                ('itemscamera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalogCameras.itemscamera')),
            ],
        ),
        migrations.AddField(
            model_name='itemscamera',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalogCameras.modelcamera'),
        ),
        migrations.CreateModel(
            name='FilmCamera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('markFilm', models.CharField(max_length=120)),
                ('sensibility', models.IntegerField(choices=[(50, 'Film1'), (100, 'Film2'), (200, 'Film3'), (400, 'Film4'), (800, 'Film5'), (1600, 'Film6')], default=50)),
                ('formatFilm', models.IntegerField(choices=[(35, 'Format1'), (110, 'Format2'), (220, 'Format3')], default=35)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalogCameras.camera')),
            ],
        ),
    ]
