# Generated by Django 3.2.9 on 2021-11-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalogCameras', '0002_alter_technicalsupport_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasing',
            name='camera_returned',
            field=models.BooleanField(default=True),
        ),
    ]
